import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/app/components/Home/Navbar";
import StoreProvider from "@/StoreProvider/StoreProvider";
import Footer from "./components/Home/Footer";
import Hero from "./components/Home/Hero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
      <body className="">
        <Navbar/>
        <Hero/>
        <div className="max-w-[1120px] m-auto p-5 lg:p-0">
          {children}
        </div>
        <Footer />
      </body>
    </html>
    </StoreProvider>
  );
}
